config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show, :edit, :update] do
  collection do
      get '/:id/shelf', to: 'users#shelf', as: 'shelf'
      get 'search'
    end
  member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :original_books, only: [:index, :create] do
  collection do
      get 'search'
    end
  end
  resources :colored_books, only: [:edit, :destroy]
  resources :book_reviews do
    resources :likes, only: [:create, :destroy]
  end
  resources :original_book_rankings, only: [:index]

  devise_scope :user do
    authenticated :user do
      root :to => 'book_reviews#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => "welcome#index", as: :unauthenticated_root
    end
  end
end



# / → welcome:index ( only logged out user can visit here like landing page )
# │
# ├── book_reviews  => Tilme Line (root_path)
# │
# ├── users => User List (pending)
# │     │
# │     ├── /:id => Profile
# │     │    │
# │     │    ├── /book_reviews => One's BookReviews
# │     │    │
# │     │    └── /shelf => One's Shelf
# │     │
# │     └── /search => User Search (pending)
# │
# ├── original_books
# │     │
# │     ├── /:id => Book Detail
# │     │
# │     └── /search => Book Search (AmazonAPI)
# │
# └── * => 404

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
  end

  private

  def use_before_action?
    true
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_button.html.slim
- unless current_user?(user)
  - if current_user.following?(user)
    .FollowForm.FollowButton
      = form_for(current_user.following_relationships.find_by(following_id: user.id),html: { method: :delete }, remote: true) do |f|
       = f.submit "フォロー中"
  - else
    .FollowForm.UnfollowButton
      = form_for(current_user.following_relationships.build(following_id: user.id), remote: true) do |f|
        = f.hidden_field :following_id
        = f.submit "フォロー"
- else
    .SelfFollowButton
      | ログイン中

app/views/relationships/_follow_form.html.slim
ul.Status
  li.Status__item
    = link_to user_path(user)
      span.Status__title 本棚
      span.Status__number = User.count_books(user)
  li.Status__item
    = link_to following_user_path(user)
      span.Status__title フォロー
      span.Status__number = user.followings.count
  li.Status__item
    = link_to followers_user_path(user)
      span.Status__title フォロワー
      span.Status__number = user.followers.count
= render partial: 'relationships/follow_button', locals: { user: user }

app/views/relationships/_side_follow_form.html.slim
ul.Status
  li.Status__item
    = link_to following_user_path(user)
      span.Status__title フォロー
      span.Status__number = user.followings.count
  li.Status__item
    = link_to followers_user_path(user)
      span.Status__title フォロワー
      span.Status__number = user.followers.count
= render partial: 'relationships/follow_button', locals: { user: user }

app/views/relationships/create.js.erb
$("#follow-of-<%= @user.id %>").html("<%= j(render partial: 'follow_form', locals: { user: @user }) %>")
$("#side-follow-of-<%= @user.id %>").html("<%= j(render partial: 'side_follow_form', locals: { user: @user }) %>")

app/views/relationships/destroy.js.erb
$("#follow-of-<%= @user.id %>").html("<%= j(render partial: 'follow_form', locals: { user: @user }) %>")
$("#side-follow-of-<%= @user.id %>").html("<%= j(render partial: 'side_follow_form', locals: { user: @user }) %>")