config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show, :edit, :update] do
  collection do
      get '/:id/shelf', to: 'users#shelf', as: 'shelf'
      get 'search'
    end
  member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :original_books, only: [:index, :create] do
  collection do
      get 'search'
    end
  end
  resources :colored_books, only: [:edit, :destroy]
  resources :book_reviews do
    resources :likes, only: [:create, :destroy]
  end
  resources :original_book_rankings, only: [:index]

  devise_scope :user do
    authenticated :user do
      root :to => 'book_reviews#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => "welcome#index", as: :unauthenticated_root
    end
  end
end



# / → welcome:index ( only logged out user can visit here like landing page )
# │
# ├── book_reviews  => Tilme Line (root_path)
# │
# ├── users => User List (pending)
# │     │
# │     ├── /:id => Profile
# │     │    │
# │     │    ├── /book_reviews => One's BookReviews
# │     │    │
# │     │    └── /shelf => One's Shelf
# │     │
# │     └── /search => User Search (pending)
# │
# ├── original_books
# │     │
# │     ├── /:id => Book Detail
# │     │
# │     └── /search => Book Search (AmazonAPI)
# │
# └── * => 404

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book_review, optional: true, counter_cache: :likes_count
  belongs_to :user
  belongs_to :comment, optional: true, counter_cache: :comments_count
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_review
  def create
    @like = Like.create(user_id: current_user.id, book_review_id: params[:book_review_id], comment_id: params[:comment_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, book_review_id: params[:book_review_id], comment_id: params[:comment_id])
    like.destroy
  end

  private
  def like_params
    params.permit(
      :user_id,
      :book_review_id,
      :comment_id
    )
  end

  def set_review
    @book_review = BookReview.find(params[:book_review_id])
  end

  def use_before_action?
    true
  end
end

app/views/likes/_like.html.slim
- if user_signed_in?
  - if book_review.like_user(current_user.id)
    = button_to book_review_like_path(Like, book_review_id: book_review.id), method: :delete, id: "like-button", remote: true do
      i.fa.fa-heart.fa-red.fa-2x
      span = book_review.likes.count
  - else
    = button_to book_review_likes_path(book_review_id: book_review.id), method: :post, id: "unlike-button", remote: true do
      i.fa.fa-heart-o.fa-2x
      span = book_review.likes.count
- else
  = book_review.likes.count
  i.fa.fa-heart.fa-red.fa-2x

app/views/likes/create.js.erb
$("#like-of-<%= @book_review.id %>").html("<%= j(render partial: 'like', locals: { book_review: @book_review }) %>")

app/views/likes/destroy.js.erb
$("#like-of-<%= @book_review.id %>").html("<%= j(render partial: 'like', locals: { book_review: @book_review }) %>");