config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show, :edit, :update] do
  collection do
      get '/:id/shelf', to: 'users#shelf', as: 'shelf'
      get 'search'
    end
  member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :original_books, only: [:index, :create] do
  collection do
      get 'search'
    end
  end
  resources :colored_books, only: [:edit, :destroy]
  resources :book_reviews do
    resources :likes, only: [:create, :destroy]
  end
  resources :original_book_rankings, only: [:index]

  devise_scope :user do
    authenticated :user do
      root :to => 'book_reviews#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => "welcome#index", as: :unauthenticated_root
    end
  end
end



# / → welcome:index ( only logged out user can visit here like landing page )
# │
# ├── book_reviews  => Tilme Line (root_path)
# │
# ├── users => User List (pending)
# │     │
# │     ├── /:id => Profile
# │     │    │
# │     │    ├── /book_reviews => One's BookReviews
# │     │    │
# │     │    └── /shelf => One's Shelf
# │     │
# │     └── /search => User Search (pending)
# │
# ├── original_books
# │     │
# │     ├── /:id => Book Detail
# │     │
# │     └── /search => Book Search (AmazonAPI)
# │
# └── * => 404

app/views/common/modal/_edit_button.html.slim
.modal-button ステータスを変更する

app/views/common/modal/_for_original_book.html.slim
.modal-contents
  = original_book.title
  = image_tag(original_book.image_url, style: "width: 70px;height: 100px;display: inline-block;")
  div 現在のstatus:#{check_shelved(original_book.isbn)}

  ul.regisration-items
    li.regisration-item
      /.read-item data-book="#{original_book.to_json}"
      - if check_shelved(original_book.isbn) == "read"
        = link_to check_read_status(check_shelved(original_book.isbn)), shelved_book_path(get_shelved_book_id(original_book.isbn)), method: :delete
      - else
        = link_to check_read_status(check_shelved(original_book.isbn)), original_books_path(set_book(original_book,"read")), method: :post
    li.regisration-item
      /.tsundoku-item data-book="#{original_book.to_json}" #{check_tsundoku_status(check_shelved(original_book.isbn))}
      - if check_shelved(original_book.isbn) == "tsundoku"
        = link_to check_tsundoku_status(check_shelved(original_book.isbn)), shelved_book_path(get_shelved_book_id(original_book.isbn)), method: :delete
      - else
        = link_to check_tsundoku_status(check_shelved(original_book.isbn)), original_books_path(set_book(original_book,"tsundoku")), method: :post
    li.regisration-item
      /.wish-item data-book="#{original_book.to_json}" #{check_wish_status(check_shelved(original_book.isbn))}
      - if check_shelved(original_book.isbn) == "wish"
        = link_to check_wish_status(check_shelved(original_book.isbn)), shelved_book_path(get_shelved_book_id(original_book.isbn)), method: :delete
      - else
        = link_to check_wish_status(check_shelved(original_book.isbn)), original_books_path(set_book(original_book,"wish")), method: :post
  a#modal-close.button-link 閉じる

app/views/common/modal/_modal.html.slim
.Modal
  .Model__inner
    .Modal__header
      h1 本を登録する
      i.fa.fa-times#modal-close aria-hidden="true"
    .Modal__content
      .Modal__book__info
        - if original_book.image_url.present?
          = image_tag original_book.image_url, class: "Modal__pic"
        - else
          = image_tag 'no_image.png', class: "Modal__pic"
        .Modal__text
          .Modal__title = original_book.title
          .Modal__author = original_book.author
      ul.Modal__action
        - if check_colored(original_book.isbn) == "read"
          li.Modal__item.already
            = link_to  colored_book_path(get_colored_book_id(original_book.isbn)), method: :delete
              i.fa.fa-check-square-o aria-hidden="true"
              = check_read_status(check_colored(original_book.isbn))
        - else
          li.Modal__item
            = link_to  original_books_path(set_book(original_book,"read", "add")), method: :post
              i.fa.fa-check-square-o aria-hidden="true"
              = check_read_status(check_colored(original_book.isbn))
        - if check_colored(original_book.isbn) == "tsundoku"
          li.Modal__item.already
            = link_to colored_book_path(get_colored_book_id(original_book.isbn)), method: :delete
              i.fa.fa-archive aria-hidden="true"
              = check_tsundoku_status(check_colored(original_book.isbn))
        - else
          li.Modal__item
            = link_to original_books_path(set_book(original_book,"tsundoku", "add")), method: :post
              i.fa.fa-archive aria-hidden="true"
              = check_tsundoku_status(check_colored(original_book.isbn))
        - if check_colored(original_book.isbn) == "wish"
          li.Modal__item.already
            = link_to colored_book_path(get_colored_book_id(original_book.isbn)), method: :delete
              i.fa.fa-list-ul aria-hidden="true"
              = check_wish_status(check_colored(original_book.isbn))
        - else
          li.Modal__item
            = link_to original_books_path(set_book(original_book,"wish", "add")), method: :post
              i.fa.fa-list-ul aria-hidden="true"
              = check_wish_status(check_colored(original_book.isbn))
        - if check_colored(original_book.isbn) == "quit"
          li.Modal__item.already
            = link_to colored_book_path(get_colored_book_id(original_book.isbn)), method: :delete
              i.fa.fa-list-ul aria-hidden="true"
              = check_quit_status(check_colored(original_book.isbn))
        - else
          li.Modal__item
            = link_to original_books_path(set_book(original_book,"quit", "add")), method: :post
              i.fa.fa-list-ul aria-hidden="true"
              = check_quit_status(check_colored(original_book.isbn))
        - if check_book_reviewed(original_book.isbn)
          li.Modal__item.already
            = link_to edit_book_review_path(id: get_book_review_id(original_book.isbn)), method: :get
              i.fa.fa-pencil-square-o aria-hidden="true"
              | レビューを編集
        - else
          li.Modal__item
            = link_to original_books_path(set_book(original_book,"read", "book_review")), method: :post
              i.fa.fa-pencil-square-o aria-hidden="true"
              | レビューを投稿

app/views/common/modal/_register_button.html.slim
.modal-button 本を登録する