config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show, :edit, :update] do
  collection do
      get '/:id/shelf', to: 'users#shelf', as: 'shelf'
      get 'search'
    end
  member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :original_books, only: [:index, :create] do
  collection do
      get 'search'
    end
  end
  resources :colored_books, only: [:edit, :destroy]
  resources :book_reviews do
    resources :likes, only: [:create, :destroy]
  end
  resources :original_book_rankings, only: [:index]

  devise_scope :user do
    authenticated :user do
      root :to => 'book_reviews#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => "welcome#index", as: :unauthenticated_root
    end
  end
end



# / → welcome:index ( only logged out user can visit here like landing page )
# │
# ├── book_reviews  => Tilme Line (root_path)
# │
# ├── users => User List (pending)
# │     │
# │     ├── /:id => Profile
# │     │    │
# │     │    ├── /book_reviews => One's BookReviews
# │     │    │
# │     │    └── /shelf => One's Shelf
# │     │
# │     └── /search => User Search (pending)
# │
# ├── original_books
# │     │
# │     ├── /:id => Book Detail
# │     │
# │     └── /search => Book Search (AmazonAPI)
# │
# └── * => 404

app/views/common/_footer.html.slim
footer.Footer

app/views/common/_header.html.slim
header
  .Header__back
    .Header__inner
      .Header__left
        - if user_signed_in?
          .Header__button
            i.fa.fa-bars.fa-2x.Header__trigger aria-hidden="true"
            ul.Header__menu
              li.Header__menu__item
                = link_to book_reviews_path
                  i.fa.fa-home aria-hidden="true"
                  | Time Line
              li.Header__menu__item
                = link_to shelf_users_path(current_user)
                  i.fa.fa-barcode aria-hidden="true"
                  | My Shelf
              li.Header__menu__item
                = link_to user_path(current_user)
                  i.fa.fa-newspaper-o aria-hidden="true"
                  | My Reviews
              li.Header__menu__item
                = link_to original_book_rankings_path
                  i.fa.fa-flash aria-hidden="true"
                  | Ranking
        .Header__logo
          - if user_signed_in?
            = link_to book_reviews_path
              i.fa.fa-book
              h1.Header__logo__title Myshelf
          - else
            i.fa.fa-book
            h1.Logo__title Myshelf
        - if user_signed_in?
          ul.Header__navi
            li.Header__navi__item
              = link_to "TimeLine", book_reviews_path
            li.Header__navi__item
              = link_to "Shelf", shelf_users_path(current_user)
            li.Header__navi__item
              = link_to "Reviews", user_path(current_user)
            li.Header__navi__item
              = link_to "Ranking", original_book_rankings_path
      .Header__right
        - if user_signed_in?
          .Header__search
            = render partial: "common/search"
          .Header__user.UserIcon
            .UserIcon__pic
              i.fa.fa-angle-down aria-hidden="true"
              = image_tag current_user.image, alt: "no_image.png"
            ul.UserIcon__menu
              li.UserIcon__menu__item
                = link_to user_path(current_user)
                  i.fa.fa-newspaper-o aria-hidden="true"
                  | My Page
              li.UserIcon__menu__item
                = link_to edit_user_path(current_user)
                  i.fa.fa-cog aria-hidden="true"
                  | Edit Profile
              li.UserIcon__menu__item
                = link_to destroy_user_session_path, method: :delete
                  i.fa.fa-sign-out aria-hidden="true"
                  | Log Out

app/views/common/_login_logo.html.slim
.sign_up_logo
  = image_tag 'logo.png'
  small
    | 本棚をラクラク管理して、みんなで共有しよう！

app/views/common/_search.html.slim
= form_tag('/original_books/search', method: :get) do
  = text_field_tag :book, "",  id: "search", name: "keyword", placeholder: "キーワードを入力"
  button[title="本を検索" type="submit"]
    i.fa.fa-search
    span ：
    i.fa.fa-book
  button[title="ユーザー検索" type="submit" name="user_search"]
    i.fa.fa-search
    span ：
    i.fa.fa-users

app/views/common/_side.html.slim
.Side
  .Side__profile
    = image_tag @user.image, alt: "no_image.png", class: "Side__pic"
    .Side__name
      h1 = @user.name
    .Side__description
      p
        = @user.description
  .Follow id="side-follow-of-#{@user.id}"
    = render partial: 'relationships/side_follow_form', locals: { user: @user }
  ul.Side__links
    span レビュー
    li
      = link_to user_path(@user)
        i.fa.fa-newspaper-o.fa-3x aria-hidden="true"
        span.Side__links__number ：
        span.Side__links__number = User.count_book_reviews(@user)
        span.Side__links__number  件
    span 本棚
    li
      = link_to shelf_users_path(@user)
        i.fa.fa-barcode.fa-3x aria-hidden="true"
        span.Side__links__number ：
        span.Side__links__number = User.count_books(@user)
        span.Side__links__number  冊